
import { Pharmacy, Review } from './types';

export const DAKAR_CENTER = { lat: 14.716677, lng: -17.467686 };

export const PHARMACIES: Pharmacy[] = [
  {
    id: 1,
    name: 'Pharmacie Guigon',
    owner: 'Dr. Marie Fall',
    address: 'Avenue Lamine Gueye, Dakar',
    neighborhood: 'Plateau',
    phone: '33 821 21 21',
    coordinates: { lat: 14.6733, lng: -17.4334 },
    onDuty: true,
    hours: { standard: '08:00 - 20:00', onDuty: '24h/24' },
  },
  {
    id: 2,
    name: 'Pharmacie Ponty',
    owner: 'Dr. Alioune Sarr',
    address: '5 Avenue Georges Pompidou, Dakar',
    neighborhood: 'Plateau',
    phone: '33 822 56 78',
    coordinates: { lat: 14.6705, lng: -17.4358 },
    onDuty: false,
    hours: { standard: '08:30 - 21:00', onDuty: 'Fermé' },
  },
  {
    id: 3,
    name: 'Pharmacie Liberté 6',
    owner: 'Dr. Fatou Diop',
    address: 'Liberté 6 Extension, Dakar',
    neighborhood: 'Liberté',
    phone: '33 827 12 34',
    coordinates: { lat: 14.7214, lng: -17.4725 },
    onDuty: false,
    hours: { standard: '08:00 - 22:00', onDuty: 'Fermé' },
  },
  {
    id: 4,
    name: 'Pharmacie Almadies',
    owner: 'Dr. Ousmane Ndiaye',
    address: 'Route des Almadies, Dakar',
    neighborhood: 'Almadies',
    phone: '33 820 98 76',
    coordinates: { lat: 14.7370, lng: -17.5147 },
    onDuty: true,
    hours: { standard: '09:00 - 20:00', onDuty: '24h/24' },
  },
  {
    id: 5,
    name: 'Pharmacie Yoff',
    owner: 'Dr. Aissatou Gueye',
    address: 'Cité Apecsy 2, Yoff',
    neighborhood: 'Yoff',
    phone: '33 860 54 32',
    coordinates: { lat: 14.7570, lng: -17.4855 },
    onDuty: false,
    hours: { standard: '08:00 - 20:30', onDuty: 'Fermé' },
  },
  {
    id: 6,
    name: 'Pharmacie des Mamelles',
    owner: 'Dr. Moussa Sow',
    address: 'Route de l\'Aéroport, Dakar',
    neighborhood: 'Mamelles',
    phone: '33 860 11 22',
    coordinates: { lat: 14.7300, lng: -17.5000 },
    onDuty: false,
    hours: { standard: '08:30 - 21:30', onDuty: 'Fermé' },
  },
    {
    id: 7,
    name: 'Pharmacie de la Medina',
    owner: 'Dr. Cheikh Tidiane Ba',
    address: 'Rue 22x13, Médina',
    neighborhood: 'Medina',
    phone: '33 821 78 90',
    coordinates: { lat: 14.6811, lng: -17.4497 },
    onDuty: false,
    hours: { standard: '08:00 - 23:00', onDuty: 'Fermé' },
  },
  {
    id: 8,
    name: 'Pharmacie Ouest Foire',
    owner: 'Dr. Khady Thiam',
    address: 'Cité Keur Gorgui, Dakar',
    neighborhood: 'Ouest Foire',
    phone: '33 864 33 44',
    coordinates: { lat: 14.7350, lng: -17.4920 },
    onDuty: false,
    hours: { standard: '09:00 - 21:00', onDuty: 'Fermé' },
  },
  {
    id: 9,
    name: 'Pharmacie de l\'Aéroport',
    owner: 'Dr. Babacar Cissé',
    address: 'Ancienne piste, Yoff',
    neighborhood: 'Yoff',
    phone: '33 820 01 02',
    coordinates: { lat: 14.7431, lng: -17.4903 },
    onDuty: true,
    hours: { standard: '08:00 - 20:00', onDuty: '24h/24' },
  },
  {
    id: 10,
    name: 'Pharmacie Sacré-Coeur',
    owner: 'Dr. Ndèye Penda Ly',
    address: 'Sicap Sacré-Coeur 3, Dakar',
    neighborhood: 'Sacré-Coeur',
    phone: '33 827 88 99',
    coordinates: { lat: 14.7118, lng: -17.4764 },
    onDuty: false,
    hours: { standard: '08:00 - 20:00', onDuty: 'Fermé' },
  },
];

export const REVIEWS: Review[] = [
  { id: 1, pharmacyId: 1, reviewerName: 'Amina Diop', rating: 5, comment: 'Service impeccable, très professionnels et de bon conseil. Toujours un plaisir de venir ici.', createdAt: '2024-05-20T10:30:00Z' },
  { id: 2, pharmacyId: 1, reviewerName: 'Moussa Faye', rating: 4, comment: 'Pharmacie bien achalandée, mais un peu d\'attente aux heures de pointe.', createdAt: '2024-05-18T15:00:00Z' },
  { id: 3, pharmacyId: 2, reviewerName: 'Fatou Ndiaye', rating: 3, comment: 'Correct, mais le personnel pourrait être plus accueillant.', createdAt: '2024-05-19T11:00:00Z' },
  { id: 4, pharmacyId: 4, reviewerName: 'Jean-Pierre Dubois', rating: 5, comment: 'Très grande pharmacie avec beaucoup de choix. Le personnel est très compétent et disponible. Je recommande vivement.', createdAt: '2024-05-21T09:00:00Z' },
  { id: 5, pharmacyId: 4, reviewerName: 'Coumba Sarr', rating: 5, comment: 'Parfait ! Ouverte 24/24, ils m\'ont sauvé un dimanche soir. Merci !', createdAt: '2024-05-12T23:15:00Z' },
  { id: 6, pharmacyId: 3, reviewerName: 'Oumar Diallo', rating: 4, comment: 'Bon service, rapide et efficace.', createdAt: '2024-04-30T14:20:00Z' },
  { id: 7, pharmacyId: 9, reviewerName: 'Sophie Gomis', rating: 2, comment: 'Longue attente et pas très aimable. Je n\'y retournerai pas.', createdAt: '2024-05-15T18:45:00Z' },
  { id: 8, pharmacyId: 10, reviewerName: 'Abdoulaye Sow', rating: 4, comment: 'Personnel à l\'écoute et de bon conseil. Je suis satisfait.', createdAt: '2024-05-17T12:00:00Z' },
];
